### ISSUE TITLE
Issues with `fb2-reader-page-width`

### ISSUE THREAD

**Issue by vlichevsky** [jumper047/fb2-reader#4]
Calculation of page width doesn't take into account the line numbers column, when it is enabled, which results in a portion of text being cut off.

Without line numbers:
![screenshot_2021-11-10_15-20-03_1920x1080](https://user-images.githubusercontent.com/17594809/141112160-e0bb1a34-a93c-4eaa-b9d0-1e0667893a8b.png)

With line numbers:
![screenshot_2021-11-10_15-20-33_1920x1080](https://user-images.githubusercontent.com/17594809/141112203-b501c699-eb82-4ed8-baef-f05d087308f1.png)

Also `fb2-reader-page-width` should be taken into account when caching rendered fb2 files. Currently if you change the value of `fb2-reader-page-width` all cached files rendered with different page width will be displayed incorrectly.

**Comment by jumper047** [comment]
Thank you for reporting! Regarding first part - I'll try to figure out way to fix it. Seems like at least display-line-numbers-mode have no easy way to get column width. Regarding second part - yep, I'll add check to invalidate cache if current and cached page-widths are different. By the way, seems like I see another bug on attached screenshots - some titles are not centered. Can you  paste here corresponding xml?

**Comment by jumper047** [comment]
Interesting, seems like this is already known issue - joostkremers/visual-fill-column#37, but code in that fix don't work on my emacs (I don't have such variable).

**Comment by vlichevsky** [comment]
Here is the xml:
[cveyg.xml.gz](https://transfer.sh/rXP6K8/cveyg.xml.gz)

> I don't have such variable

Which variable? Do you mean the function `line-number-display-width`? It was introduced in Emacs 26.

**Comment by jumper047** [comment]
Width with line number and cache issues should be fixed, but I'll keep this issue opened because of not centered title bug.

**Comment by vlichevsky** [comment]
The issue with page width is not fixed. I see exactly the same behavior as before, cache is not invalidated (and I deleted old cache before checking, so the new version, with page width is created).

The line numbers issue is half-fixed: if line numbers are enabled when I open fb2 file and then toggled off everything looks OK, but if line numbers are initially disabled and toggled off after opening the file the text is clipped.

**Comment by jumper047** [comment]
Now these two issues are fixed I hope. Regarding third - I suppose it caused by my way of definig face and will be fixed automatically when I'll fix #6

**Comment by vlichevsky** [comment]
Yup, confirming the fixes. :+1:

**Comment by jumper047** [comment]
In last update I fixed the issue with centering titles, so I'll close this issue. Feel free to reopen if I miss something.
